server:
  port: 8000

management:
  endpoints:
    web:
      base-path: /
      exposure:
        include:
          - health
          - healthy
      path-mapping:
        health: "internal/health"
        healthy: "health"
